---
title: "Use side-view HSI data to predict A"
date: "`r Sys.Date ()`"
output:
  pdf_document: default
---

```{r, setup, include=FALSE, cache = F}
knitr::opts_chunk$set(echo = T)
knitr::opts_knit$set(root.dir = '/Users/ting15/Dropbox/Ting_Wang/rice_imaging_ms')
#knitr::opts_knit$set(root.dir = 'C:/Users/rebec/Dropbox/Ting_Wang/rice_imaging_ms')
```

```{r import packages, echo = F, include=FALSE}
rm(list = ls())
## Load package 
list.of.packages <- c("tidyverse", "dplyr", "reshape2", "ggplot2", "pls", "scales", "kableExtra", "ggpubr", "gridExtra", "CORElearn")
invisible(lapply(list.of.packages, library, character.only = TRUE))
```

```{r import data, include=FALSE}
phyraw <- read.csv('./data/ground_truth/phyraw_forHSI_2022.csv', header = T, sep = ',', dec = '.')
ref_meta <- read.csv('./data/hyperspectral_imaging/HSI_side_for_biotraits_mod_W6.csv', header = T, sep = ',', dec = '.')
ref_meta = ref_meta[ ,-c(746:762)] # remove wv > 2500
file_path <- "./results/reliefF_plsr/sideviewA/A_n_200_wv"
```

```{r functions and settings, echo=FALSE}
input_for_reliefF = function(X_IDdata, y_metadata, cal.ID, y_name, num_X_names){
  y_cal = y_metadata[y_metadata$ID %in% cal.ID, ]
  X_cal = X_IDdata[X_IDdata$ID %in% cal.ID, ]
  
  data_ID <- merge(X_cal, subset(y_cal, select = -c(Treatment, Subpop)), 
                     by = "ID")
  data <- data_ID[ ,-1] # drop ID
  names(data) = c(num_X_names, y_name)
  
  return(data)
}

reliefF_algorithm = function(pre_cal, # calibration data with full spectrum
                             y_name, num_X_names,
                             estimator = "RReliefFexpRank", iterationtimes = 100){
  
    attr <- attrEval(y_name, pre_cal, estimator = estimator,
                   ReliefIterations = nrow(pre_cal)*iterationtimes)

    attr_long <- data.frame(value = unname(attr),
                            wv = num_X_names)
    
    return(attr_long)
}

cal_val_data_sets = function(cal.ID, val.ID, 
                             X_IDdata, y_metadata, X_attr, 
                             y_name, num_X_names,
                             plot=F, y_unit=NULL){
  
  X_select <- as.matrix(X_IDdata[ ,as.character(X_attr$wv)])
  
  cal.plsr.data = data.frame(y_metadata, 
                           Spectra=I(X_select))[y_metadata$ID %in% cal.ID, ]
  #print("Cal ID: ")
  #print(as.vector(cal.plsr.data$ID))
  
  val.plsr.data = data.frame(y_metadata, 
                           Spectra=I(X_select))[y_metadata$ID %in% val.ID, ]
  #print("Val ID: ")
  #print(as.vector(val.plsr.data$ID))
  
  if (isTRUE(plot)) {
        par(mfrow=c(1,2))
    hist(cal.plsr.data[ ,y_name], main="cal", xlab=paste0(y_name, y_unit))
    hist(val.plsr.data[ ,y_name], main="val", xlab=paste0(y_name, y_unit), 
         breaks = 3)}
  
 return(list(cal.plsr.data, val.plsr.data))
}

sel_wv_plotdata = function(data){
  data.df = as.data.frame(cbind(data$Spectra))
  names(data.df) = as.numeric(attr(data$Spectra, "dimnames")[[2]])
  data.df$ID = data$ID
  data.long = melt(data.df, id = "ID") %>% 
  mutate(variable = as.numeric(as.character(variable)), .keep="unused")
  return(data.long)
}

quantile_sel_ref = function(data, lo_q, hi_q){
  summary = data %>%
  group_by(variable) %>%
  summarize(mean_value=mean(value),
            lo=quantile(value, lo_q),
            hi=quantile(value, hi_q))
  names(summary)=c("wv", "mean_ref", "lo_ref", "hi_ref")
  summary_long = melt(summary, id="wv")
  return(summary_long)
}

min_selectNcomp <- function(object, ncomp = maxComps, plot = FALSE, ...) {
    if (!isTRUE(object$validation$method == "CV"))
        stop("No cross-validation data available in model")
    ## check that Y is univariate
    if (dim(residuals(object))[2] > 1)
        stop("Only univariate response supported")
    ## includes zero component, the first element is the zero component
    rmseps <- c(RMSEP(object, "CV")$val) 
    maxIdx <- ncomp + 1
    absBest <- which.min(rmseps[seq_len(maxIdx)])
    selection <- absBest -1
    if (is.null(origResponse <- object$y))
      
        origResponse <- c(predict(object, ncomp = 1) + residuals(object)[,1,1])
    
    allresids <- cbind(origResponse-
                         (sum(origResponse)-origResponse)/(length(origResponse) - 1),
                       object$validation$pred[,1,] - origResponse)
        ## include LOO prediction with zero components (i.e., the
        ## mean). For the mean we should also use the LOO estimate...
    residsds <- apply(allresids, 2, sd) / sqrt(nrow(allresids))
    uls <- rmseps - residsds
    lls <- rmseps + residsds
    if (absBest > 0) {
      if (isTRUE(plot)) {
        par(mfrow=c(1,1), mar=c(6, 7, 1, 0.4), oma=c(0, 0.1, 0, 0.2), mgp = c(5, 2, 0))
# the first index should be zero component, but the rmseps considered it as the first element
            xvals <- seq_along(rmseps) - 1  
            plot(xvals, rmseps, ylab = "RMSEP",
                 xlab = "Number of components", type = "b", ...)
            arrows(xvals, uls, xvals, lls,
                   code = 3, col = "gray", angle = 90, length = .1)
            abline(h = rmseps[absBest], col = "gray", lty = 3)
            abline(v = absBest - 1, col = "blue", lty = 3)
        }
      selection
    } else {
        warning("Lowest CV error found at 0 components")
    }
}

plsr_results = function(model, nComps, cal.plsr.data, val.plsr.data, y_name){
  y_cal = cal.plsr.data[ ,y_name]
  y_cal_fit = model$fitted.values[,,nComps]
  PLSR_CV_Predicted = as.vector(model$validation$pred[,,nComps])
  PLSR_CV_Residuals = PLSR_CV_Predicted-y_cal
  #intercept = F, estimates for a model with zero component does not need to be returned
  cal.R2 <- round(pls::R2(model,intercept=F)[[1]][nComps],3) 
  cal.RMSEP <- round(sqrt(mean(PLSR_CV_Residuals^2)),3)
  cal_y_range <- range(y_cal)[2]-range(y_cal)[1]
  cal.NRMSEP <- round((sqrt(mean(PLSR_CV_Residuals^2))/cal_y_range)*100, 3) 
  
  y_val = val.plsr.data[ ,y_name]
  y_val_fit = as.vector(
    predict(model,newdata = val.plsr.data,ncomp=nComps,type="response")[,,])
  y_val_resids =  y_val_fit-y_val
  val.R2 <- round(pls::R2(model,newdata=val.plsr.data,intercept=F)[[1]][nComps],3)
  val.RMSEP <- round(sqrt(mean(y_val_resids^2)),3)
  val_y_range <- range(y_val)[2]-range(y_val)[1]
  val.NRMSEP <- round((sqrt(mean(y_val_resids^2))/val_y_range)*100,3)
  
  mm=data.frame(
    data_set=c("cal", "val"),
    R2 = c(cal.R2, val.R2),
    RMSEP = c(cal.RMSEP, val.RMSEP),
    NRMSEP = c(cal.NRMSEP, val.NRMSEP)
  )
  cal.plsr.output = data.frame(Observed = y_cal,
                               Predicted = PLSR_CV_Predicted,
                               Residuals = PLSR_CV_Residuals,
                               Treatment = cal.plsr.data$Treatment,
                               Subpop = cal.plsr.data$Subpop)
  val.plsr.output = data.frame(Observed = y_val,
                               Predicted = y_val_fit,
                               Residuals = y_val_resids,
                               Treatment = val.plsr.data$Treatment,
                               Subpop = val.plsr.data$Subpop)
  list = list(cal.plsr.output = cal.plsr.output, 
              val.plsr.output = val.plsr.output, 
              mm = mm)
  return(list)
           
}
`%notin%` <- Negate(`%in%`)

# plsr setting
pls::pls.options(plsralg = "oscorespls")
pls::pls.options("plsralg")
opar <- par(no.readonly = T)

# plot spectra color settings
summary_ref_col = c("mean_ref" = "forestgreen", "lo_ref"="green", "hi_ref"="green")

# plot prediction color and shape settings
subpop_col = c("TRJ" = 'blue', 'IND' = 'red')
treatment_shape = c('N1' = 16, 'N2' = 1)
```

```{r data, echo = F}
y_metadata <- phyraw %>%
  select("ID", "A", "Treatment", "Subpop") %>%
  mutate(ID = as.factor(ID)) %>%
  na.omit() 

X_IDdata <- ref_meta %>%
  select(!c(Accession, Subpop, Country, Treatment)) %>%
  mutate(ID = as.factor(ID)) %>%
  filter(ID %in% y_metadata$ID)
num_X_names = as.numeric(gsub("_", ".", sub("...", "",  names(X_IDdata[,-1]))))
names(X_IDdata) = c("ID", as.character(num_X_names))

cal.ID <- y_metadata %>% 
  select(ID, Treatment) %>%
  group_by_at(vars(all_of("Treatment"))) %>%
  slice(sample(1:n(), 0.8*n())) %>% 
  ungroup()%>% select(-Treatment)%>% as.matrix() %>% as.vector()

val.ID = as.character(y_metadata[!y_metadata$ID %in% cal.ID, "ID"])

print(cal.ID)
print(val.ID)
``` 

```{r feature selection, echo=FALSE}
pre_cal = input_for_reliefF(X_IDdata = X_IDdata, y_metadata = y_metadata, 
                            cal.ID = cal.ID, y_name = 'A', 
                            num_X_names = num_X_names)

reliefF = reliefF_algorithm(pre_cal = pre_cal, 
                                y_name = 'A', num_X_names = num_X_names) 
reliefF_star =  reliefF[order(reliefF$value, decreasing = T)[1:200], ] 
tail(reliefF_star)
```

```{r cal and vel data sets, echo = F, fig.align='center', fig.width = 9, fig.height = 5}
cal_val_list = cal_val_data_sets(cal.ID = cal.ID, val.ID = val.ID,
                                   X_IDdata = X_IDdata, y_metadata = y_metadata, 
                                   X_attr = reliefF_star, 
                                   y_name = 'A', num_X_names = num_X_names,
                                   plot = T, y_unit = expression(" ("~mu*mol~m^-2~s^-1~")"))

cal.plsr.data = cal_val_list[[1]]
val.plsr.data = cal_val_list[[2]]
```

```{r spectra in cal and val data sets, echo=FALSE, fig.align='center', fig.width = 9, fig.height = 6}
cal.plsr.long = sel_wv_plotdata(cal.plsr.data)
val.plsr.long = sel_wv_plotdata(val.plsr.data)

sel_wv_ref_min = range(cal.plsr.long$value, val.plsr.long$value)[1]
sel_wv_ref_max = range(cal.plsr.long$value, val.plsr.long$value)[2]

summary_cal_long = quantile_sel_ref(data = cal.plsr.long, 0.025, 0.975)
summary_val_long = quantile_sel_ref(data = val.plsr.long, 0.025, 0.975)

cal_ref_95perc = ggplot()+
  geom_point(aes(x=variable, y=value, group=ID), data=cal.plsr.long,
             size=0.3, color="grey")+
  geom_point(aes(x=wv, y=value, col=variable), data = summary_cal_long, 
             size=0.5, show.legend = F)+
  scale_color_manual(values = summary_ref_col)+
  scale_y_continuous(breaks = seq(sel_wv_ref_min, sel_wv_ref_max, length.out = 3), 
                     labels = round(seq(sel_wv_ref_min, sel_wv_ref_max, length.out = 3), 3),
                     limits = c(sel_wv_ref_min, sel_wv_ref_max)) +
  labs(title = "A calibration dataset", x= "Wavelength (nm)", y = "Reflectance (%)") +
  theme_bw(base_size=18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        )

val_ref_95perc = ggplot()+
  geom_point(aes(x=variable, y=value, group=ID), data=val.plsr.long,
             size=0.3, color="grey")+
  geom_point(aes(x=wv, y=value, col=variable), data = summary_val_long, 
             size=0.5, show.legend = F)+
  scale_color_manual(values = summary_ref_col)+
  scale_y_continuous(breaks = seq(sel_wv_ref_min, sel_wv_ref_max, length.out = 3), 
                     labels = round(seq(sel_wv_ref_min, sel_wv_ref_max, length.out = 3), 3),
                     limits = c(sel_wv_ref_min, sel_wv_ref_max)) +
  labs(title = "A validation dataset", x= "Wavelength (nm)", y = "Reflectance (%)") +
  theme_bw(base_size=18) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        ) 

ref_95perc = ggarrange(cal_ref_95perc, val_ref_95perc, nrow = 2)
ref_95perc
```

```{r selected wv, echo=FALSE}
full_spectra_calID = melt(X_IDdata[X_IDdata$ID %in% cal.ID, -1]) #remove ID

full_spectra_calID_summary = full_spectra_calID %>%
  group_by(variable) %>%
  summarize(mean = mean(value),
            lo = quantile(value, 0.025),
            hi = quantile(value, 0.975)) %>%
  mutate(wv = as.numeric(as.character(variable)))

selected_wv = ggplot()+
  geom_vline(aes(xintercept=variable), data=cal.plsr.long, color = "green") + 
  geom_ribbon(aes(x = wv, ymin = lo, ymax=hi), 
              fill = 'grey70', data = full_spectra_calID_summary) +
  geom_line(aes(x = wv, y = mean), data = full_spectra_calID_summary) +
  theme_bw()+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
        ) +
  labs(x='Wavelength (nm)', y = 'Reflectance (%)')
selected_wv
```

```{r number of components CV, echo = F, fig.align='center', fig.width = 4, fig.height = 5}
plsr.ini <- plsr(A~Spectra, scale=FALSE,
                 validation="LOO",trace=FALSE,data=cal.plsr.data)
maxComps <- 15
pdf(file = paste0(file_path, "/A_nComps.pdf"), bg = "white", width = 7, height = 5)
par(mfrow=c(1,1), mar=c(6,7,1,0.5), oma=c(0, 0.1, 0, 0.2), mgp = c(3, 1, 0))
nComps = min_selectNcomp(plsr.ini,plot = T,
                lwd=1.6,xlim = c(0, maxComps),pch=21, col="black", 
                bg = "grey70", cex.axis = 2, cex.lab = 2, font.lab = 2, font = 2)
dev.off()
```
   
```{r plsr output, echo = F}
plsr.out <- plsr(A~Spectra, scale=FALSE, ncomp = nComps,
                 validation="LOO",trace=FALSE,data=cal.plsr.data, jackknife=T)

plsr.output.data = plsr_results(model=plsr.out, 
                                      nComps=nComps,
                                      cal.plsr.data=cal.plsr.data,
                                      val.plsr.data=val.plsr.data,
                                      y_name='A')
print(plsr.output.data$mm)

cal.plsr.output = plsr.output.data$cal.plsr.output
#head(cal.plsr.output)
val.plsr.output = plsr.output.data$val.plsr.output
#head(val.plsr.output)
```

```{r jackknife coef, echo=FALSE}
jackknife = spectratrait::f.coef.valid(plsr.out, 
                                             cal.plsr.data, 
                                             nComps, 'A')
intercepts = jackknife[1,,,]
coefs = jackknife[-1,,,]
pred_jackknife = matrix(rep(intercepts, length(val.plsr.data[,'A'])), byrow = T,
                          ncol = length(intercepts))+ 
                   val.plsr.data$Spectra %*% coefs 

val.plsr.output$uci = apply(pred_jackknife, 1, quantile, 0.975)
val.plsr.output$lci = apply(pred_jackknife, 1, quantile, 0.025)

model_sd_mean = apply(pred_jackknife, 1, sd)
model_sd_res = sd(val.plsr.output$Residuals)
modle_totsd = sqrt(model_sd_mean^2 + model_sd_res^2)

val.plsr.output$upi = val.plsr.output$uci + 1.96*modle_totsd
val.plsr.output$lpi = val.plsr.output$lci - 1.96*modle_totsd
head(val.plsr.output)
```

```{r cal scatter, echo=FALSE}
rng = range(val.plsr.output$upi, val.plsr.output$lpi,
            val.plsr.output$Observed, val.plsr.output$Predicted,
            cal.plsr.output$Observed, cal.plsr.output$Predicted)
text_xloc_n <- seq(round(rng[1]), round(rng[2]), length = 10)[3]
text_yloc_n <- (rng[2]-rng[1])/60*58+rng[1]
text_xloc_mm <- seq(round(rng[1]), round(rng[2]), length = 10)[6]
text_y_R2 <- (rng[2]-rng[1])/10*2.1+rng[1]
text_y_RMSEP <- (rng[2]-rng[1])/10*1.2+rng[1]
text_y_NRMSEP <- (rng[2]-rng[1])/10*0.3+rng[1]

cal_scatter_plot <- ggplot(cal.plsr.output, aes(x=Observed, y=Predicted)) + 
  geom_abline(intercept = 0, slope = 1, size=0.3) + 
  geom_point(aes(col=Subpop, shape = Treatment)) + 
  scale_color_manual(values = subpop_col)+
  scale_shape_manual(values = treatment_shape)+
  #geom_smooth(method = "lm", formula = y ~ x, se = F) +
  scale_x_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  scale_y_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  theme_bw(base_size = 6) + 
  labs(x=expression("\n Observed: A ("~mu*mol~m^-2~s^-1~")"),
       y=expression("Predicted: A ("~mu*mol~m^-2~s^-1~")")) +
  theme(legend.position="none") + 
 annotate("text", size = 2 , x= text_xloc_mm, y = c(text_y_R2, text_y_RMSEP), parse = TRUE, 
           label = c(paste("R^{2} == ", plsr.output.data$mm[1,"R2"]), 
                     paste("RMSEP ==", plsr.output.data$mm[1,"RMSEP"]))) +
 annotate("text", size = 2 , x= text_xloc_mm, y = text_y_NRMSEP, 
           label = "%RMSEP = 14.62") +
 annotate("text", x = text_xloc_n, y = text_yloc_n, parse = T, 
           label = "Cal. (italic(n) == 74)", size = 2)
cal_scatter_plot
```

```{r cal residuals plot, echo=FALSE}
cal_resid_plot <- ggplot(cal.plsr.output, aes(x=Observed, y=Residuals)) + 
  geom_hline(yintercept = 0, size = 0.3)+
  geom_point(aes(col=Subpop, shape = Treatment)) + 
  scale_color_manual(values = subpop_col)+
  scale_shape_manual(values = treatment_shape)+
  theme_bw(base_size = 6)+
  theme(legend.position="none") + 
  labs(x=expression("\n Observed: A ("~mu*mol~m^-2~s^-1~")"),
       y="Residuals")

cal_resid_plot 
```

```{r val CI plot, echo=FALSE}
val_CI_plot <- ggplot(val.plsr.output, aes(x=Observed, y=Predicted)) +
  geom_abline(intercept = 0, slope = 1, size=0.3) + 
  geom_point(aes(col=Subpop, shape = Treatment)) + 
  scale_shape_manual(values = treatment_shape)+
  geom_errorbar(aes(ymin = lci, ymax = uci,col=Subpop), width=0.05) +
  scale_color_manual(values = subpop_col)+
  #geom_smooth(method = "lm", formula = y ~ x, se = F) +
  scale_x_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  scale_y_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  theme_bw(base_size = 6) + 
  labs(x=expression("\n Observed: A ("~mu*mol~m^-2~s^-1~")"),
       y=expression("Predicted: A ("~mu*mol~m^-2~s^-1~")")) +
  theme(legend.position="none") + 
  annotate("text", size = 2 , x= text_xloc_mm, y = c(text_y_R2, text_y_RMSEP), parse = TRUE, 
           label = c(paste("R^{2} == ", plsr.output.data$mm[2,"R2"]), 
                     paste("RMSEP ==", plsr.output.data$mm[2,"RMSEP"]))) +
  annotate("text", size = 2 , x= text_xloc_mm, y = text_y_NRMSEP, 
           label = "%RMSEP = 38.42") +
  annotate("text", x = text_xloc_n, y = text_yloc_n, parse = T, 
           label = "Val. (italic(n) == 20)", size = 2)
val_CI_plot
```

```{r val PI plot, echo=FALSE}
val_PI_plot <- ggplot(val.plsr.output, aes(x=Observed, y=Predicted)) +
  geom_abline(intercept = 0, slope = 1, size=0.3) + 
  geom_point(aes(col=Subpop, shape = Treatment)) + 
  scale_shape_manual(values = treatment_shape)+
  geom_errorbar(aes(ymin = lpi, ymax = upi, col=Subpop), width=0.05) +
  scale_color_manual(values = subpop_col)+
  #geom_smooth(method = "lm", formula = y ~ x, se = F) +
  scale_x_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  scale_y_continuous(breaks = seq(round(rng[1]), round(rng[2]), length = 5), 
                     labels = seq(round(rng[1]), round(rng[2]), length = 5), 
                     limits = c(rng[1], rng[2]))+
  theme_bw(base_size = 6) + 
  labs(x=expression("\n Observed: A ("~mu*mol~m^-2~s^-1~")"),
       y=expression("Predicted: A ("~mu*mol~m^-2~s^-1~")")) +
  theme(legend.position="none") + 
  annotate("text", size = 2 , x= text_xloc_mm, y = c(text_y_R2, text_y_RMSEP), parse = TRUE, 
           label = c(paste("R^{2} == ", plsr.output.data$mm[2,"R2"]), 
                     paste("RMSEP ==", plsr.output.data$mm[2,"RMSEP"]))) +
  annotate("text", size = 2 , x= text_xloc_mm, y = text_y_NRMSEP, 
           label = "%RMSEP = 38.42") +
  annotate("text", x = text_xloc_n, y = text_yloc_n, parse = T, 
           label = "Val. (italic(n) == 20)", size = 2)
val_PI_plot
```

```{r val residuals plot, echo=FALSE}
val_resid_plot <- ggplot(val.plsr.output, aes(x=Observed, y=Residuals)) + 
  geom_hline(yintercept = 0, size = 0.3)+
  geom_point(aes(col=Subpop, shape = Treatment)) + 
  scale_color_manual(values = subpop_col)+
  scale_shape_manual(values = treatment_shape)+
  theme_bw(base_size = 6)+
  theme(legend.position="none") + 
  labs(x=expression("\n Observed: A ("~mu*mol~m^-2~s^-1~")"),
       y="Residuals")

val_resid_plot 
```

```{r prepare jk coef for output, echo=FALSE}
out.jk.coefs <- data.frame(Iteration=seq(1,length(intercepts),1),
                           Intercept=intercepts, t(coefs)) 
head(out.jk.coefs)[1:6]
```

```{r prepare coef in final model for output, echo=FALSE}
coefs = data.frame(
  coefs = coef(plsr.out)[,1,1])
head(coefs)
```

```{r save plots and data}
ggsave(filename = paste0(file_path, "/A_cal_scatter_plot.pdf"), 
       plot = cal_scatter_plot, 
       device = "pdf", width = 3.5, height = 3.5, units = "cm", dpi = 400)

ggsave(filename = paste0(file_path, "/A_cal_resid_plot.pdf"), 
       plot = cal_resid_plot, 
       device = "pdf", width = 3.5, height = 3.5, units = "cm", dpi = 400)

ggsave(filename = paste0(file_path, "/A_val_CI_plot.pdf"), 
       plot = val_CI_plot, 
       device = "pdf", width = 3.5, height = 3.5, units = "cm", dpi = 400)

ggsave(filename = paste0(file_path, "/A_val_PI_plot.pdf"), 
       plot = val_PI_plot, 
       device = "pdf", width = 3.5, height = 3.5, units = "cm", dpi = 400)

ggsave(filename = paste0(file_path, "/A_val_resid_plot.pdf"), 
       plot = val_resid_plot, 
       device = "pdf", width = 3.5, height = 3.5, units = "cm", dpi = 400)

ggsave(filename = paste0(file_path, "/A_selected_wv.pdf"), 
       plot = selected_wv, 
       device = "pdf", width = 7, height = 5, units = "cm", dpi = 400)

write.csv(x=reliefF, 
          file = paste0(file_path, "/A_reliefF_200.csv"), 
          row.names = F)
write.csv(x=cal.plsr.output, 
          file = paste0(file_path, "/A.cal.plsr.output.csv"), 
          row.names = F)
write.csv(x=val.plsr.output, 
          file = paste0(file_path, "/A.val.plsr.output.csv"), 
          row.names = F)
write.csv(x=out.jk.coefs, 
          file = paste0(file_path, "/A_out.jk.coefs.csv"), 
          row.names = F)
write.csv(x=coefs, 
          file = paste0(file_path, "/A_coefs.csv"), 
          row.names = T)
```
